### ISSUE TITLE
Realm accessed from incorrect thread, help needed

### ISSUE THREAD

**Issue by nmtitov** [realm/realm-cocoa#1953]
How can I debug `Realm accessed from incorrect thread` error? I want to know what object or operation is the reason of this error. Basically I use Realm for tasks like this one. I want to mark local objects as deleted, synced, updated and so on depending on server response. AFNetworking performs callbacks on main thread. I use [RLMRealm defaultRealm] everywhere.

````
// this is called from main thread
- (void)deleteFromServer {
    RLMResults *xs = [Entity objectsWhere:@"shouldDelete = YES"];
    for (id *x in xs) {
        [self deleteEntityFromServer:x];
    }
}

- (void)deleteEntityFromServer:(Entity *)entity {
    NSString *endpoint = @"...";
    
    [self.http DELETE:endpoint parameters:nil completion:^(OVCResponse *resp, NSError *err) {
            [[RLMRealm defaultRealm] beginWriteTransaction];
            entity.deleted = YES;  // this is called from main thread too
            [[RLMRealm defaultRealm] commitWriteTransaction];
        }
    }];
}
````

I added logging of current thread, but it seems to be the same every time

````
2015-05-17 16:40:27.100 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.102 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:27.114 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.117 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:27.137 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.141 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:27.164 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.167 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:27.178 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.179 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:27.737 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.745 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:27.780 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.782 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:27.811 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:27.812 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.117 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.119 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.135 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.137 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.156 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.159 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.180 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.185 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.202 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.204 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.228 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.231 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.307 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.308 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.330 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.332 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.359 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.360 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.401 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.403 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.542 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.544 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.569 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.571 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.592 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.594 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.707 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.709 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.730 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.732 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.753 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.755 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.783 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.785 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.866 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.868 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.913 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.915 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:28.968 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:28.970 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.015 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.017 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.065 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.067 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.110 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.113 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.168 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.170 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.198 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.200 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.246 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.248 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.299 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.301 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.340 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.342 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.386 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.388 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.540 App[7836:60b] __37-[MyService uploadEntities]_block_invoke, exists
2015-05-17 16:40:29.542 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.565 App[7836:60b] __37-[MyService uploadEntities]_block_invoke_2, find
2015-05-17 16:40:29.567 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
2015-05-17 16:40:29.596 App[7836:60b] __37-[MyService uploadEntities]_block_invoke_2, find
2015-05-17 16:40:29.598 App[7836:60b] Running on <NSThread: 0x14d56100>{name = (null), num = 1} thread
````

And then I get `0x3ecc90 <+280>: b      0x3ecca4                  ; <+300> at RLMObjectBase.mm:188`

![screen shot 2015-05-17 at 16 50 12](https://cloud.githubusercontent.com/assets/193307/7670833/35223686-fcbd-11e4-9e93-1ad8cd1d655e.png)

What could be wrong here?

**Comment by nmtitov** [comment]
I also added this check in every place where I use RLMObjects `NSCAssert([NSThread isMainThread], @"");`

**Comment by hermanolsson** [comment]
Realm Cocoa 0.92 introduced a thread check in -[RLMObjectBase dealloc] (#1727), and strongly capturing "entity" in the completion block probably causes this issue, since AFNetworking might retain/release the block on a different thread.

I'm struggling a bit myself with this, and to avoid it I use weak reference in situations like this.

Have a look at #1893 for more information. Also, to the really smart people at Realm: Please forgive me if this was not a totally accurate answer.

**Comment by RyanCopley** [comment]
@nmtitov store your objects primary key, then while inside the AFNetworking call, re-fetch the object with `[RLMObject objectForPrimaryKey:]`. There *is* a bug that will give you grief if your HTTP request fails, however. AFNetworking is releasing objects on its own thread, and Realm throws an exception

**Comment by nmtitov** [comment]
@RyanCopley you mean, whatever I do, if AFNetworking receives error, dealloc would crash?

**Comment by RyanCopley** [comment]
Until https://github.com/realm/realm-cocoa/issues/1893 is resolved -- to my understanding, yes. I am not a Realm dev though, so I could be wrong.

**Comment by nmtitov** [comment]
@RyanCopley I tried to do it this way, but still get crashes. This should be same as `primaryKey`, right?:

````
- (void)deleteEntityFromServer:(Entity *)entity {
    NSString *endpoint = @"...";
    long serverID = entity.serverID;
    [self.http DELETE:endpoint parameters:nil completion:^(OVCResponse *resp, NSError *err) {
            [[RLMRealm defaultRealm] beginWriteTransaction];
            RLMResults *results = [Entity objectsWhere:@"serverID = %ld", serverID];
            Entity *entity = results.firstObject;
            entity.deleted = YES;  // this is called from main thread too
            [[RLMRealm defaultRealm] commitWriteTransaction];
        }
    }];
}
````

And it's important for me to receive server errors. I could rewrite server API to return success with `error` description or switch to another networking library.

**Comment by RyanCopley** [comment]
Rewriting your server API would be futile-- what if they're in airplane mode? I am hoping that they release a fix soon.

**Comment by RyanCopley** [comment]
Ignoring the warning for now, try this:

```
    self.http.completionQueue = dispatch_get_current_queue();
```

**Comment by nmtitov** [comment]
Thanks, I didn't try that yet (eventually block would perform on main thread since dispatch_get_current_queue(); would return main queue and then block will be deallocated somewhere else in the guts of AFNetworking in case of error, it would still crash?).

What I did:

1) Created EntityUpdateMessage message for each operation

@interface EntityUpdateMessage : NSObject

@property (assign, nonatomic) long serverID;
@property (copy, nonatomic) NSString *baz;
@property (assign, nonatomic) long foo;
@property (assign, nonatomic) BOOL bar;

@end

2) Wrote this method which makes AFNetworking calls. This method is called from for..in loop over RLMObjects, so I pull values from RLMObjects and pass them to this method. AFNetworking blocks don't catch RLMObjects, just values.

`- (void)uploadEnitityWithServerID:(long)serverID foo:(NSString *)foo bar:(NSString *)bar baz:(BOOL)baz;`

3) In AFNetworking responses I create `EntityUpdateMessage` objects and pass them to "handler" this way:
````
- (void)uploadEnitityWithServerID:(long)serverID foo:(NSString *)foo bar:(NSString *)bar baz:(BOOL)baz {
    NSDictionary *params = @{
        @"serverID": @(serverID),
    };
    @weakify(self);
    [App().http GET:@"foo/bar/" parameters:params completion:^(...) {
            // ...
            [App().http GET:@"baz/" parameters:params completion:^(...) {
                @strongify(self);
                if (resp.HTTPResponse.statusCode == 200) {
                    EntityMantle *serverEntity = resp.result;
                    if (!serverEntity) {
                        return;
                    }
                    
                    EntityUpdateMessage *entityUpdateMessage = [[EntityUpdateMessage alloc] init];
                    entityUpdateMessage.serverID = serverID;
                    entityUpdateMessage.foo = foo;
                    entityUpdateMessage.bar = serverEntity.bar;
                    entityUpdateMessage.baz = serverEntity.baz;
                    
                    [self performSelector:@selector(updatedEntityWithMessage:) entityUpdateMessage afterDelay:0];
                    return;
                }
            }];
            
            return;
        }
```` 

4) Added this convenience function

- (void)updatedEntityWithMessage:(EntityUpdateMessage *)entityUpdateMessage {
    [self updatedEntityWithServerID:entityUpdateMessage.serverID ...]; // (unwrap entityUpdateMessage)
}

5) And added handler, which works with Realm
````
- (void)updatedEntityWithServerID:(long)serverID foo:(id)foo bar:(id)bar baz(id)baz {
    [App() checkMainThread];
    
    NSLog(@"%s, update entity with::", __PRETTY_FUNCTION__);
    NSLog(@"Running on %@ thread", [NSThread currentThread]);

    Entity *entity = [Entity objectForPrimaryKey:@(serverID)];
    RLMResults *childEntities = [entity.childEntities objectsWhere:@"serverID = %lu", serverID];
    ChildEntity *childEntitiy = childEntities.firstObject;
    if (!childEntitiy) {
        return;
    }
    // Finally :-)
    [[RLMRealm defaultRealm] beginWriteTransaction];
    childEntitiy.foo = foo;
    childEntitiy.bar = bar;
    [[RLMRealm defaultRealm] commitWriteTransaction];
}
````

I don't know if this is correct at all, but I just managed to upload some entities to server and it makes me happy. I've been struggling with this for several days.

**Comment by nmtitov** [comment]
Basically I could use `RACTuple` instead of class and two functions, but I wanted to make it simple. My idea was to prevent AFNetworking blocks from capturing RLMObject instances.

**Comment by jpsim** [comment]
Thanks everyone for chiming in on this thread. #1984 should allow thread-safe object deallocation, which should land shortly.
