### ISSUE TITLE
xcodebuild faild: 'collection_notifications.hpp' file not found

### ISSUE THREAD

**Issue by devedbox** [realm/realm-cocoa#4330]
Version 2.0.4 file not found when using cocoapods trunk push command.

## Goals

To be able to compile successfully.

## Expected Results

No errors occur.

## Actual Results

Build failed with error:

```
#include "collection_notifications.hpp"
         ^
1 error generated.
```

## Steps to Reproduce

`pod trunk push --verbose --allow-warnings`

## Code Sample

```
/var/folders/m1/vyls4x9167b98rtbtwmyvjnw0000gp/T/CocoaPods/Lint/Pods/Realm/Realm/ObjectStore/src/impl/collection_change_builder.cpp:19:10: fatal error: 'impl/collection_change_builder.hpp' file not found
#include "impl/collection_change_builder.hpp"
         ^

CompileC /Users/devedbox/Library/Developer/Xcode/DerivedData/App-gyjmrpvlfiduejbdxaszesswculw/Build/Intermediates/Pods.build/Release-iphonesimulator/Realm.build/Objects-normal/i386/collection_notifications.o Realm/Realm/ObjectStore/src/collection_notifications.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler

/var/folders/m1/vyls4x9167b98rtbtwmyvjnw0000gp/T/CocoaPods/Lint/Pods/Realm/Realm/ObjectStore/src/collection_notifications.cpp:19:10: fatal error: 'collection_notifications.hpp' file not found
#include "collection_notifications.hpp"

 - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
  - NOTE  | [iOS] xcodebuild:  Realm/Realm/ObjectStore/src/impl/collection_change_builder.cpp:19:10: fatal error: 'impl/collection_change_builder.hpp' file not found
    - NOTE  | [iOS] xcodebuild:  Realm/Realm/ObjectStore/src/collection_notifications.cpp:19:10: fatal error: 'collection_notifications.hpp' file not found
```
## Version of Realm and Tooling

```
Realm version: 2.0.4

Xcode version: 8.1

iOS/OSX version: 10.12.1

Dependency manager + version: 1.0.0

ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

/Applications/Xcode.app/Contents/Developer
Xcode 8.1
Build version 8B62

/usr/local/bin/pod
1.1.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/bin/git
git version 2.9.3 (Apple Git-75)
```

**Comment by jpsim** [comment]
Hi @devedbox, are you trying to push `Realm.podspec`, `RealmSwift.podspec` or a different podspec altogether?

If you're using Realm in a different podspec and you're specifying a location other than CocoaPods trunk, make sure you set it to use git submodules, as the Realm pods depend on those.

If you're trying to push `Realm.podspec` or `RealmSwift.podspec` to say your own private CocoaPods trunk server, make sure you've updated your local submodules prior to doing so:

```
git submodule update --init --recursive
```

And that you're using the latest version of CocoaPods (1.1.1), and that you have Xcode 8.x installed and `xcode-select`ed. I just pushed the `Realm` and `RealmSwift` pods version 2.0.4 yesterday to CocoaPods trunk with no issue.

**Comment by devedbox** [comment]
@jpsim I tried as you said and still failed. this is my podspec file:
```
Pod::Spec.new do |s|

  s.name         = 'JYObjectModule'
  s.version      = '0.0.27'
  s.summary      = 'A module of models definition.'
  s.description  = <<-DESC
                    A module of models definition on iOS platform for jiangyou tec. only.
                   DESC

  s.homepage     = 'https://github.com/jiangtour/JYObjectModule'
  s.license      = { :type => 'MIT', :file => 'LICENSE' }

  s.author             = { 'aiXing' => '862099730@qq.com' }
  s.platform     = :ios, '7.0'

  s.source       = { :git => 'https://github.com/jiangtour/JYObjectModule.git', :tag => '0.0.27' , :submodules => true }
  s.source_files  = 'JYObjectModule/Models/*.{h,m}', 'JYObjectModule/Models/Normal/*.{h,m}', 'JYObjectModule/Models/Storage/*.{h,m}'

  s.frameworks = 'Foundation'

  s.requires_arc = true
  s.dependency 'Realm'
  s.dependency 'MJExtension'
  s.dependency 'SDWebImage'
  s.dependency 'CocoaSecurity'
  s.dependency 'UICKeyChainStore'

end
```
It works fine in version 2.0.3.

**Comment by devedbox** [comment]
I add `realm-object-store` as a submodule and build successfully. You can close the issue now. Thanks anyway. @jpsim

**Comment by jpsim** [comment]
Glad to hear it!

**Comment by amit-k-gupta** [comment]
Hi,

I am using RealmSwift and getting the same issue. Both cocoapod and realm are latest version.

**Comment by jpsim** [comment]
@amit-k-gupta please file a new issue with steps to reproduce, and please include the _entire_ output from `pod install -verbose`

**Comment by mathroule** [comment]
Same issue using RealmSwift _v2.1.1_, no problem with _v2.1.0_.

**Comment by jpsim** [comment]
@mathroule please file a new issue with steps to reproduce, and please include the _entire_ output from `pod install -verbose`, and taking care to fill out all the sections in the new issue template.

I'll be closing this issue to prevent future messages being posted without including the necessary information prompted by the issue template. Thanks for understanding!
