### ISSUE TITLE
Unable to initialize Realm database, most likely due to corrupt database

### ISSUE THREAD

**Issue by EmDee** [realm/realm-cocoa#5809]
## Goals
Finding out why database can't be initialized.

## Expected Results

Correctly initializing database.

## Actual Results

Trying to initialize a Realm instance is failing for hundreds of our users.

## Steps to Reproduce

Unfortunately, we tried everything imaginable to reproduce the error, but haven't succeeded so far.

## Code Sample

You can see most parts of our database class here: https://gist.github.com/EmDee/2b69181f4376a629bbb7f9b13d2c5dbf

The problem is in https://gist.github.com/EmDee/2b69181f4376a629bbb7f9b13d2c5dbf#file-database-swift-L61:

```swift
guard let realm = try? Realm(configuration: realmConfig) else {
    nonFatalErrorOccurred("Error while starting db operation")
}
```

`nonFatalErrorOccurred(_:String)` is just a way for us to pass around errors that are then later reported to our crash reporting/logging.

At some point our users keep ending up in the `else case` of this `guard`, and will be stuck until the app is removed and installed again, thus we highly assume that the Realm database is corrupt at this point.

Our stack traces of those `nonFatalErrorOccurred(_:String)` usually look like the following:

```swift
OurKit error: Error while starting db operation

0  OurApp                  nonFatalErrorOccurred (AppStateCoordinator+OurKitDelegate.swift)
1  OurApp                  nonFatalErrorOccurred (OurKit.swift:257:27)
2  OurApp                  nonFatalErrorOccurred (Database.swift)
3  OurApp                  getRealm (Trip.swift)
4  OurApp                  reabstraction thunk helper from @callee_guaranteed () -> (@error @owned Swift.Error) to @callee_guaranteed () -> (@out (), @error @owned Swift.Error) (DatastoreInterface.swift)
5  OurApp                  partial apply forwarder for reabstraction thunk helper from @callee_guaranteed () -> (@error @owned Swift.Error) to @callee_guaranteed () -> (@out (), @error @owned Swift.Error) (CloudSync+Trips.swift)
6  libswiftObjectiveC.dylib swift_rt_swift_release
7  OurApp                  getUncreated (Trip.swift:169:9)
8  OurApp                  syncTrips (CloudSync+Trips.swift:43:9)
9  OurApp                  partial apply forwarder for closure #1 () -> () in closure #1 () -> () in static OurKit.CloudSync.requestSync(for: OurKit.CloudSync.SyncType, force: Swift.Bool) -> () (CloudSync.swift:66:30)
10 OurApp                  reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> () (DebuggingProtocol.swift)
11 libdispatch.dylib        __dispatch_block_async_invoke2
12 libdispatch.dylib        __dispatch_client_callout
13 libdispatch.dylib        __dispatch_continuation_pop$VARIANT$mp
14 libdispatch.dylib        __dispatch_source_invoke$VARIANT$mp
15 libdispatch.dylib        __dispatch_queue_serial_drain$VARIANT$mp
16 libdispatch.dylib        __dispatch_queue_invoke$VARIANT$mp
17 libdispatch.dylib        __dispatch_root_queue_drain_deferred_wlh$VARIANT$mp
18 libdispatch.dylib        __dispatch_workloop_worker_thread$VARIANT$mp
19 libsystem_pthread.dylib  __pthread_wqthread
20 libsystem_pthread.dylib  _start_wqthread
```

`syncTrips (CloudSync+Trips.swift:43:9)` in the stack trace basically calls `getUncreated (Trip.swift:169:9)`  which in return looks like this:

```swift
static func getUncreated() -> [Trip] {
    var result: [Trip] = []

    autoreleasepool {
        if let realm = Database.getRealm() {
            result = realm.objects(Trip.self)
                .filter(NSPredicate(format: "%K == false", Fields.syncing))
                .map { $0 }
        }
    }

    return result
}
```

And at `Database.getRealm()` is where it will run into the before mentioned instantiation of Realm and fail.

Our app is writing quite a bit to the database, roughly every 200ms data is written to the database. We know of the problem of accessing a Realm database from background threads, thus we wrapped everything in `autoreleasepool`. We've tried our best to break the database so that our code would fail at the guard statement, but we weren't able to.

### What we've tried

- modifying the Realm file (means changing the file protection) while transaction were happening
- accessing the Realm database from multiple random background thread, while simultaneously deleting all the content of the database
- combinations of app being in foreground, background, locked with passcode, without passcode, phone screen off/on.

### Basically the current questions we have are:

- Are we doing something fundamentally wrong in our way of working with Realm?
- Can it sometimes happen that a Realm database can't be initialized other than the database being corrupt?

If you should need our whole project, we will gladly send it to help@realm.io, however, the codes above represents quite well, how we are working with Realm.

## Version of Realm and Tooling

It has happened with every Realm framework version that we've had in our production code so far.

Realm framework version: `v3.6.0`

Realm Object Server version: -

Xcode version: We have build the app with multiple different Xcode versions. The most recent one being 9.3.1 where the crashes are still occurring.

iOS/OSX version: `9.0 - 11.4`

Dependency manager + version: `Carthage, 0.29.0`

**Comment by EmDee** [comment]
Btw: We are assuming that some sort of memory leak or memory shortage might be the problem here, but couldn't verify so far. Could it be that if not enough memory is available that the Realm database cannot be loaded into memory, which then leads to the `guard else case` being triggered?

**Comment by tgoyne** [comment]
Catching the actual error thrown and logging that rather than discarding it with `try?` may give more information.

**Comment by EmDee** [comment]
@tgoyne
I forgot to mention this, but yes, that’s what we are doing for our upcoming release. We just started tracking this exception with our last release, but didn’t think that many people will run into this problem, thus haven’t wrapped it in a catch block.

**Comment by EmDee** [comment]
We just released our newest version and this is the error message that we're getting:

`Error while accessing database: Unable to open a realm at path '/var/mobile/Containers/Data/Application/$APP_UUID/Documents/appName/appName.realm.management/access_control.write.mx': open() failed: Operation not permitted.`

**Comment by EmDee** [comment]
@tgoyne 
We did some more investigation and more logging.

Our fix seems to fail for the `access_control.write.mx` file. The localized description is `Die Datei „access_control.write.mx“ konnte nicht geöffnet werden, da du nicht die Zugriffsrechte hast, um sie anzuzeigen.` so roughly translated to `file couldn't be opened, due to missing permissions`.

Any ideas how that can happen? The `appName.realm.management` directory definitely doesn't have any file protection set, as shown our log regarding its attribute:

```
"realmManagementDirectory": {
    "NSFileOwnerAccountID": 501,
    "isReadable": true,
    "NSFileExtensionHidden": false,
    "isExecutable": true,
    "NSFileSystemFileNumber": 237565,
    "NSFileSize": 192,
    "NSFileProtectionKey": "NSFileProtectionNone",
    "NSFilePosixPermissions": 493,
    "NSFileGroupOwnerAccountID": 501,
    "NSFileSystemNumber": 16777218,
    "NSFileExtendedAttributes": {},
    "NSFileType": "NSFileTypeDirectory",
    "isWritable": true,
    "NSFileGroupOwnerAccountName": "mobile",
    "NSFileReferenceCount": 6,
    "NSFileOwnerAccountName": "mobile"
  }
```

**Comment by EmDee** [comment]
Ping

**Comment by tgoyne** [comment]
The `.mx` files are named pipes so permissions for them are somewhat odd, but I still don't see anything obviously wrong there. If that's the permissions for the directory, maybe the permissions for the files inside the directory are different though?

You can safely delete the contents of the `management` directory while the Realm isn't open (doing so while the Realm is open will result in strange bugs and/or crashes), and doing so before opening the Realm may be sufficient to work around whatever's wrong?

**Comment by EmDee** [comment]
> If that's the permissions for the directory, maybe the permissions for the files inside the directory are different though?

Usually files created in a directory should inherit its parent's permissions.

> You can safely delete the contents of the management directory while the Realm isn't open (doing so while the Realm is open will result in strange bugs and/or crashes)

Great, good to know. This wouldn't fix the cause, but we might still try this as a workaround. I'll report back, as soon as we've tested this.

**Comment by bmunkholm** [comment]
@EmDee No to the last question. It just means that it's not currently in a write transaction.

**Comment by EmDee** [comment]
I'm assuming that we have a false positive here. Will open a new ticket if we run into this problem again.
