### ISSUE TITLE
Lexical or Preprocessor Issue

### ISSUE THREAD

**Issue by lawgimenez** [realm/realm-cocoa#5882]
## Goals

Compile `pod 'RealmSwift', '3.7.6'` successfully

## Expected Results

Build successful

## Actual Results

After updating to `pod 'RealmSwift', '3.7.6'` it throws an error Lexical or Preprocessor Issue with the description of `'binding_callback_thread_observer.hpp' file not found`

## Steps to Reproduce

Run `pod 'RealmSwift', '3.7.6'`

## Version of Realm and Tooling

Realm framework version: 3.7.6

Realm Object Server version: ?

Xcode version: 9.4.1

iOS/OSX version: ?

Dependency manager + version: 1.5.3

**Comment by rjndra** [comment]
For me this issue was resolved by cleaning project and doing `pod update`.
I also tried installing particular build for my running swift version.
In pod file

Below code from source:  [here](https://www.cerebralgardens.com/blog/entry/2017/10/04/mix-and-match-swift-3-swift-4-libraries-with-cocoapods)
```
post_install do |installer|
    print "Setting the default SWIFT_VERSION to 4.0\n"
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
    end

    installer.pods_project.targets.each do |target|
        if ['SomeTarget-iOS', 'SomeTarget-watchOS'].include? "#{target}"
            print "Setting #{target}'s SWIFT_VERSION to 3.0\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        else
            print "Setting #{target}'s SWIFT_VERSION to Undefined (Xcode will automatically resolve)\n"
            target.build_configurations.each do |config|
                config.build_settings.delete('SWIFT_VERSION')
            end
        end
    end
end

```

**Comment by lawgimenez** [comment]
Thanks but as much as possible I don't want to complicate things. Realm has been compiling with no problem for over the past year on iOS on my end. So hopefully this gets resolved. I also did clean-rebuild and pod updates with still no luck.

**Comment by stennie** [comment]
Closing this issue with no recent activity. I assume this issue has been resolved -- please let us know if that is not the case.
