### ISSUE TITLE
Semantic issues with versions > 5.1.0

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [realm/realm-cocoa#6664]
## Goals
Use a version of RealmSwift > 5.1.0

## Expected Results
No error building app after installing > 5.1.0

## Actual Results
The app fails to compile with a bunch of semantic issues:
```
...app/Pods/Realm/include/core/__bit_reference:176:62: No member named '__libcpp_ctz' in namespace 'std::__1'; did you mean '__libcpp_wcsstr'?
...app/Pods/Realm/include/core/__bit_reference:1119:7: No template named '_If'
etc
```

## Steps for others to Reproduce
Execute `pod update` with `pod 'RealmSwift'` in the Podfile
Try to run the app and it will throw errors
Specify `pod 'RealmSwift', '5.1.0'` instead and it runs successfully

## Version of Realm and Tooling
Realm framework version: 5.3.1 or anything > 5.1.0

Xcode version: 11.6 (11E708)

iOS/OSX version: iOS 13.6, macOS 10.15.6

Dependency manager + version: CocoaPods 1.9.3

Let me know if you need any more info!

**Comment by tgoyne** [comment]
Do you have Xcode 12 installed and set as the default Xcode version? `pod install` needs to be run with the same Xcode version as you're going to build the project as we set things up differently for each of them. Deleting the Pods directory and rerunning `pod install` with Xcode 11 active selected should fix it.

If you don't have Xcode 12 installed at all then that'd mean there's a bug in how we're detecting the active Xcode version.

**Comment by jordanhbuiltbyhq** [comment]
I do! Switched to Xcode 11 via xcode-select, made sure command line tools is Xcode 11, deleted Pods and reran pod install but I still get the same errors. 🤔

**Comment by bsweett** [comment]
I am see a similar issue in Xcode 11.5 but only with 5.3.2. I was able to revert to 5.3.1 and the issue went away. 5.3.2 builds correctly in Xcode 12 beta 3.

**Comment by tgoyne** [comment]
This should go away in the next release as the bug we were working around (incorrectly?) appears to have been fixed in Xcode 12 beta 3.

**Comment by bsweett** [comment]
This has been fixed. I tested with 5.3.5 and Xcode 12 beta 5.
