### ISSUE TITLE
Realm.object returns NIL object when queried by primary key in Realm 10.0 beta2

### ISSUE THREAD

**Issue by ramjyroo** [realm/realm-cocoa#6672]
!!! MANDATORY TO FILL OUT !!!
## Goals
I have signed up with MongoDB Realm and installed the beta SDK. I have a Local Realm file that NEED not be synced with cloud. It is prepopulated with data and during app install - I move it to documents folder of the iOS (All this is existing code and works well when using the normal Realm SDK 4.4.x or 5.3.x). 

After login to the Realm App - other than the Synced Realm, I also open this Non-Synced local realm using a different configuration. 
As the Grade class is NOT synced - I have NOT added the partition key or used _id as primary key.
```
class Grade: Object {
    @objc dynamic var id=""
    @objc dynamic var sno=0
    @objc dynamic var name=""
    @objc dynamic var version=0
    @objc dynamic var timestamp = Date()
    let linkedPrimarySkills = List<String>()
    override static func primaryKey() -> String? {
        return "id"
    }
    
    override static func indexedProperties() -> [String] {
        return ["sno", "name"]
    }
}
func sample() {
var config = Realm.Configuration(schemaVersion: 83)
guard let fileUrl = config.fileURL else {
    throw AppError.invalidState("fileURL of realm config is nil")
}
config.fileURL = fileUrl.deletingLastPathComponent().appendingPathComponent("content.realm")
config.readOnly = false
let realm = try Realm(configuration: config)
let grades = realm.objects(Grade.self)
grades.forEach { (grade) in
   print(grade) // prints all the objects as expected - I just added this to debug the issue to ensure objects exists
}
// note: I have opened the Realm file using Studio and data is present
guard let grade3 = realm.object(ofType: Grade.self, forPrimaryKey: "003") else {
   print("G3 Not queryable by primary key") // prints this even that object is very much present
   return // this is where it returns
}
print(grade3) // Never reaches here
}
```
I'm trying to query a object from Non-Synced Realm

## Expected Results
Since the object is present - Non-Nil object should be returned

## Actual Results
Even though the object is present - the realm.object function call returns NIL

I have tried using the realm.objects to dump all the objects in the specific collection - It lists down all the objects. But when using primary key - every object return nil.

It is NOT a read-only realm
## Code Sample
Shared above

## Version of Realm and Tooling
10.0.0-beta.2

Realm framework version: ?

Realm Object Server version: ?
Using MongoRealm

Xcode version: ?
11.5

iOS/OSX version: ?
13.5 

Dependency manager + version: ?
CocoaPods

**Comment by ramjyroo** [comment]
As explained above - while `let grade3 = realm.object(ofType: Grade.self, forPrimaryKey: "003")` is returning NIL - I'm able to do use the filtered query `let filtered = grades.filter(NSPredicate(format: "id == %@", "003"))` to find the record.

So definitely looks like a bug

**Comment by ericjordanmossman** [comment]
@ramjyroo 
Thanks for the detailed information. I'm working on this issue today. 

> After login to the Realm App - other than the Synced Realm, I also open this Non-Synced local realm using a different configuration.

Could you share the sync configuration? 1) Does it include the `Grade` class? 2) What is the partition key on the configuration? These details may inform some testing.

**Comment by ramjyroo** [comment]
No the sync configuration was plainly based on the User object as shown in your documentation. I did use the objectTypes property to restrict my synced realm to just 1 Test Class that I used for my testing - this was to ensure Grade class was not picked up by Synced realm.

**Comment by ericjordanmossman** [comment]
@ramjyroo 
Could you take at [this repository](https://github.com/ericjordanmossman/rc6672) and make any changes/notes on where your application flow may differ?

I receive this from the `results` and `object(ofType: class.self, forPrimaryKey: key)`:
```
// print(results)
Results<LocalClass> <0x7f94e940ca00> (
	[0] LocalClass {
		_id = 1;
		sno = 0;
		name = 9811E905-EF78-4922-AAA0-4A5990E18AFE;
		version = 0;
		timestamp = 2020-07-29 17:59:48 +0000;
		linkedPrimarySkills = List<string> <0x600002130280> (
		
		);
	},
	[1] LocalClass {
		_id = 0;
		sno = 0;
		name = C8B30968-1633-4D32-895C-CEA4C110076D;
		version = 0;
		timestamp = 2020-07-29 17:59:48 +0000;
		linkedPrimarySkills = List<string> <0x600002130140> (
		
		);
	},
	[2] LocalClass {
		_id = 2;
		sno = 0;
		name = 424DDC29-AC14-491D-8FEA-81CDC7D5EE9E;
		version = 0;
		timestamp = 2020-07-29 17:59:48 +0000;
		linkedPrimarySkills = List<string> <0x6000021300a0> (
		
		);
	}
)
// realm.object(ofType: LocalClass.self, forPrimaryKey: "1")
LocalClass {
	_id = 1;
	sno = 0;
	name = 9811E905-EF78-4922-AAA0-4A5990E18AFE;
	version = 0;
	timestamp = 2020-07-29 17:59:48 +0000;
	linkedPrimarySkills = List<string> <0x6000021143c0> (
	
	);
}
```

I'm wondering if I'm missing something relevant in:

- order of the realm files being opened
- operations against the different realm files (and the order of those actions)
- how bundling/copying of realm files to local directory occurs
- the objects of the local realm file.

If you can, feel free to make changes to get the project into a reproducible state. This would help a great deal.

**Comment by ramjyroo** [comment]
@ericjordanmossman - One main difference is that my original realm file was created using realm 4.4.x and got auto upgraded  when I opened the app using the beta.

**Comment by ericjordanmossman** [comment]
@ramjyroo 
That was it. Thanks! 
Using a file upgraded from 4.4.1 shows this:
```
//  let objectFromPredicate = results.filter(NSPredicate(format: "_id == %@", "1")).first
Optional(LocalClass {
	_id = 1;
	sno = 0;
	name = C11598EA-FFC6-43FE-ACC1-2E8E6C0CA658;
	version = 0;
	timestamp = 2020-07-31 17:43:36 +0000;
	linkedPrimarySkills = List<string> <0x600001b121c0> (
	
	);
})
//  let objectFromPrimaryKey = realm.object(ofType: LocalClass.self, forPrimaryKey: "1")
nil
```

**Comment by ericjordanmossman** [comment]
It looks like when trying to retrieve by primary key, the object is always considered invalid in [RLMGetObject](https://github.com/realm/realm-cocoa/blob/v10.0.0-beta.2/Realm/RLMObjectStore.mm#L223), returning nil.

@tgoyne 
In realm-cocoa 4.4.1 `is_valid()` was determined by whether a row accessor [was attached](https://github.com/realm/realm-object-store/blob/92503d750cab072b3b78cf1dd696e63081c83d6a/src/object.hpp#L64) to the row:
`bool is_valid() const { return m_row.is_attached(); }`

10.0.0-beta.2 uses [m_obj.is_valid](https://github.com/realm/realm-object-store/blob/c02707bc28e1886970c5da29ef481dc0cb6c3dd8/src/object.hpp#L91).
`bool is_valid() const { return m_obj.is_valid(); }`

But objects created in a Realm 4.4.1 file will be `m_valid = false` by the time they get [here](https://github.com/realm/realm-core/blob/v10.0.0-beta.1/src/realm/obj.cpp#L169). Where should `m_valid` be set originally?

**Comment by ramjyroo** [comment]
> @ramjyroo
> That was it. Thanks!
> Using a file upgraded from 4.4.1 shows this:
> 
> ```
> //  let objectFromPredicate = results.filter(NSPredicate(format: "_id == %@", "1")).first
> Optional(LocalClass {
> 	_id = 1;
> 	sno = 0;
> 	name = C11598EA-FFC6-43FE-ACC1-2E8E6C0CA658;
> 	version = 0;
> 	timestamp = 2020-07-31 17:43:36 +0000;
> 	linkedPrimarySkills = List<string> <0x600001b121c0> (
> 	
> 	);
> })
> //  let objectFromPrimaryKey = realm.object(ofType: LocalClass.self, forPrimaryKey: "1")
> nil
> ```

Thanks for finding the root cause !!

**Comment by tgoyne** [comment]
This has been fixed in core, but we haven't made a v10 beta release with the fix yet.

**Comment by duncangroenewald** [comment]
@tgoyne - I just posted an issue with this same problem using v5.3.5 when upgrading from a v4.4.1 realm. I see above you indicate this has been fixed in core - can you confirm whether this fix has yet to be merged into v5.x builds ?  If so when do you anticipate doing this - just want to know when to check back since this is the last main issue holding us back from upgrading production.

BTW the thread id fix you posted earlier has resolved the random crashes now - thanks for that.

**Comment by ericjordanmossman** [comment]
@duncangroenewald 
Please see our latest v10, [beta.4](https://github.com/realm/realm-cocoa/releases/tag/v10.0.0-beta.4)
I'll close this issue. If the you still see the same issue please comment.

**Comment by duncangroenewald** [comment]
@ericjordanmossman I thought this patch was only was only merged into realm-core 6.0.24

**Comment by duncangroenewald** [comment]
@ericjordanmossman - yes I just tried 5.3.6 and still the same problem.  I did check the commit merges and thought the patch was only merged into 6.0.24 so if someone could push out a realm-swift 5.3.7 with realm-core 6.0.24 that might do it.

Thanks

**Comment by ericjordanmossman** [comment]
@duncangroenewald Ah - understood, thanks. I'll connect with the rest  of the team. I'll continue to comment on #6716 .

**Comment by duncangroenewald** [comment]
Ok I see it's 5.4.0 that is being built.

**Comment by duncangroenewald** [comment]
Problem is fixed in 5.4.0.  Thanks

**Comment by hyouuu** [comment]
@ericjordanmossman I'm still seeing the problem with the latest 5.4.7, upgrading from 4.3.0. Do you know if there has been regressions on this issue since 5.4.0?
