### ISSUE TITLE
Cannot compile using RealmSwift via Swift Package Manager in Xcode 12

### ISSUE THREAD

**Issue by FaultyJuggler** [realm/realm-cocoa#6923]
## Goals
Integrate RealmSwift using Swift Package Manager

## Expected Results
Project will compile

## Actual Results
Compilation errors

## Steps for others to Reproduce
Add Realm via swift package manager to a project (possibly that previously had Realm added via cocoapods)

## Code Sample
Compile warnings
```
found duplicate sources declaration in the package manifest: /Users/felip/Library/Developer/Xcode/DerivedData/CashBack-eywfvhinxnkbqvaftrufrscenkit/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/src/util/scheduler.cpp

ignoring broken symlink /Users/felip/Library/Developer/Xcode/DerivedData/CashBack-eywfvhinxnkbqvaftrufrscenkit/SourcePackages/checkouts/realm-cocoa/include/Realm/RLMUsernamePasswordProviderClient.h

ignoring broken symlink /Users/felip/Library/Developer/Xcode/DerivedData/CashBack-eywfvhinxnkbqvaftrufrscenkit/SourcePackages/checkouts/realm-cocoa/include/Realm/RLMAppCredentials.h

ignoring broken symlink /Users/felip/Library/Developer/Xcode/DerivedData/CashBack-eywfvhinxnkbqvaftrufrscenkit/SourcePackages/checkouts/realm-cocoa/include/Realm/RLMSyncUser.h

ignoring broken symlink /Users/felip/Library/Developer/Xcode/DerivedData/CashBack-eywfvhinxnkbqvaftrufrscenkit/SourcePackages/checkouts/realm-cocoa/include/Realm/RLMUserAPIKeyProviderClient.h
```

## Version of Realm and Tooling
Realm framework version: 10.1.2

Xcode version: Version 12.1 (12A7403)

iOS/OSX version: 14

Dependency manager + version: swift package manager

**Comment by pavel-ship-it** [comment]
Hi @FaultyJuggler ,
Could you please give me more details? Is the problem happened because of the Compile warnings above or is it something else? Another kind of error?

**Comment by FaultyJuggler** [comment]
@pavel-ship-it I've been having blocking issues with using Cocoapods and have also found cocoapods very fragile once you start using more than a single library.  I removed all cocoapods from the project, imported everything via Swift Package Manager, and when I went to compile and have following errors (I assume related to the warnings above):

```
SceneDelegate.swift:12:11: Cannot find 'App' in scope
LoginViewController.swift:113:32: Cannot find 'Credentials' in scope
GroupsTableViewController.swift:31:52: Value of type 'SyncConfiguration' has no member 'partitionValue'
PricesViewController.swift:39:52: Value of type 'SyncConfiguration' has no member 'partitionValue'
RetailersViewController.swift:28:48: Value of type 'SyncConfiguration' has no member 'partitionValue'
```

**Comment by theolampert** [comment]
@FaultyJuggler I think the sync parts of Realm just don't work with SPM, I've had the same issue for a while (wanting to switch away from Cocoapods). I assumed now with the official release that SPM was supported but seems it's not the case.

**Comment by pavel-ship-it** [comment]
Yes, it is not supported in SPM configuration yet.
@FaultyJuggler taking in account the issue with cocoapod binaries you've mentioned in previous ticket I'd recommend to try Carthage.

**Comment by duncangroenewald** [comment]
I am also trying to build a dynamic library with Carthage but when I run carthage update nothing gets built.  Is there a problem with using Carthage and Xcode 12.2 ?

**Comment by jsflax** [comment]
@FaultyJuggler , we're currently working on a full SPM release that supports Sync. We'll update this ticket when that occurs.

**Comment by duncangroenewald** [comment]
@jsflax - I see there is a v10.1.3 build that includes arm64, can you confirm this includes the sync component and can you also confirm that there is a v5.5.x build coming that will include arm64 and Sync.  

Thanks

**Comment by leemaguire** [comment]
@duncangroenewald our latest version of Realm v10.5.0 has full arm64 & Sync support via SPM. We have no plans on retrofitting support to the v5.5.x versions, and recommend always to use the latest version of Realm.

**Comment by leemaguire** [comment]
Closing this as the original issue has been solved with full SPM support.

**Comment by theolampert** [comment]
@leemaguire Is this Xcode 12.3 only? I just tried compiling in 12.2 and hit a few issues.

**Comment by duncangroenewald** [comment]
> @duncangroenewald our latest version of Realm v10.5.0 has full arm64 & Sync support via SPM. We have no plans on retrofitting support to the v5.5.x versions, and recommend to always use the latest version of Realm.

But in practice v10.5.0 does not support Realm Cloud and MongoDB Realm is not ready for production use yet!!

**Comment by theolampert** [comment]
@leemaguire This still doesn't build with Xcode 12.3 and SPM
```
<unknown>:0: error: module map file '/RealmSwift/RealmSwift.modulemap' not found
<unknown>:0: error: module map file '/RealmSwift/RealmSwift.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'
```
