### ISSUE TITLE
realmWithPath method crashes

### ISSUE THREAD

**Issue by kevinnguy** [realm/realm-cocoa#933]
When I call:

```
[RLMRealm realmWithPath:@"example.realm"]
```

It crashes and logs:

```
Terminating app due to uncaught exception 'RLMException', reason: 'open() failed: Operation not permitted'
```

How do I create a specific realm file besides using default.realm and `[RLMRealm defaultRealm]`? Am I missing something from the documentation?

It breaks in `group_shared.hpp` 

```
#ifdef TIGHTDB_ENABLE_REPLICATION
inline SharedGroup::SharedGroup(Replication& repl):
    m_group(Group::shared_tag()),
    m_transactions_are_pinned(false)
{
    open(repl);
}
#endif
```

**Comment by abdulrauf618** [comment]
I am facing error simile to it in swifit, please let me know whats happening wrong,

2015-05-30 17:55:01.007 Rufi[7200:156255] *** Terminating app due to uncaught exception 'RLMException', reason: 'open() failed: No such file or directory'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000103217c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000104d85bb7 objc_exception_throw + 45
	2   Realm                               0x0000000102dc3293 _Z18RLMSetErrorOrThrowP7NSErrorPU15__autoreleasingS0_ + 176
	3   Realm                               0x0000000102db55c6 -[RLMRealm initWithPath:key:readOnly:inMemory:dynamic:error:] + 2409
	4   Realm                               0x0000000102db5e2c +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] + 595
	5   Realm                               0x0000000102db5a34 +[RLMRealm realmWithPath:readOnly:error:] + 51
	6   RealmSwift                          0x0000000102d26e45 _TFC10RealmSwift5RealmCfMS0_FT4pathSS_S0_ + 101
	7   Rufi                             0x0000000102c46fff _TFC7Rufi9Dashboard11viewDidLoadfS0_FT_T_ + 543
	8   Rufi                             0x0000000102c475b2 _TToFC7Rufi9Dashboard11viewDidLoadfS0_FT_T_ + 34
	9   UIKit                               0x0000000103be9210 -[UIViewController loadViewIfRequired] + 738
	10  UIKit                               0x0000000103c1901b -[UINavigationController _layoutViewController:] + 44
	11  UIKit                               0x0000000103c19565 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 216
	12  UIKit                               0x0000000103c19664 -[UINavigationController _startTransition:fromViewController:toViewController:] + 92
	13  UIKit                               0x0000000103c1a448 -[UINavigationController _startDeferredTransitionIfNeeded:] + 523
	14  UIKit                               0x0000000103c1af0e -[UINavigationController __viewWillLayoutSubviews] + 43
	15  UIKit                               0x0000000103d65715 -[UILayoutContainerView layoutSubviews] + 202
	16  UIKit                               0x0000000103b38a2b -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 536
	17  QuartzCore                          0x0000000108586ec2 -[CALayer layoutSublayers] + 146
	18  QuartzCore                          0x000000010857b6d6 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
	19  QuartzCore                          0x000000010857b546 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	20  QuartzCore                          0x00000001084e7886 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 242
	21  QuartzCore                          0x00000001084e8a3a _ZN2CA11Transaction6commitEv + 462
	22  UIKit                               0x0000000103ab6a2d -[UIApplication _reportMainSceneUpdateFinished:] + 44
	23  UIKit                               0x0000000103ab76f1 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2648
	24  UIKit                               0x0000000103ab60d5 -[UIApplication workspaceDidEndTransaction:] + 179
	25  FrontBoardServices                  0x00000001077375e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	26  CoreFoundation                      0x000000010314b41c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	27  CoreFoundation                      0x0000000103141165 __CFRunLoopDoBlocks + 341
	28  CoreFoundation                      0x0000000103140f25 __CFRunLoopRun + 2389
	29  CoreFoundation                      0x0000000103140366 CFRunLoopRunSpecific + 470
	30  UIKit                               0x0000000103ab5b42 -[UIApplication _run] + 413
	31  UIKit                               0x0000000103ab8900 UIApplicationMain + 1282
	32  Rufi                             0x0000000102c55877 main + 135
	33  libdyld.dylib                       0x0000000105520145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jpsim** [comment]
@abdulrauf618 could you please file a new issue? Thanks.

**Comment by abdulrauf618** [comment]
thanks @jpsim I fixed it.

**Comment by martinliu0** [comment]
@abdulrauf618 how did you fix it?

**Comment by abdulrauf618** [comment]
@martinliu0 : In our case we were doing a mistake in integration, when I double check the things that issue were fixed.

Check you integration steps.

Realm team have example code, so check example project also hope, it will help you.

**Comment by richardoti** [comment]
@abdulrauf618 having the same issue. Could you clarify which mistakes can lead to it? Works fine in Swift 1.2, issue is reproducible only in Swift 2.0

**Comment by AndrewBarba** [comment]
If anyone else comes across this I believe this is the function you're looking for [RLMRealmPathForFile](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealmConfiguration.mm)

However, I use this function and am still seeing crashes being reported in Crashlytics. The thing is, I've never seen the app crash and none of my testers have reported crashes so I wonder if it has to do with starting the app in the background. Are write permissions different when iOS launches the app to perform a background fetch? 

I know when iOS 7 first came out there were a lot of issues with the Keychain and background fetch so I wonder if there is something similar going on here.
